### ISSUE TITLE
Configuration Tree Diagram 

### ISSUE THREAD

**Issue by fiservedpi** [recyclarr/wiki#16]
If possible please include config tree diagrams when providing code snips. 
for example [https://recyclarr.dev/wiki/yaml/config-reference/custom-formats/](url)

`# See "Basic Setup" for `service_type` and `instance_name`
service_type:
  instance_name:
    # Quality Definition Configuration
    quality_definition:
      type: series
      preferred_ratio: 0.5 `

but it’s not apparent where this snip should be added to 

I’d like to see something like this tree outlining where things should be placed, after the snip if possible
![image](https://github.com/recyclarr/wiki/assets/42981853/092fe9f6-cb31-4b15-97fd-871c6462abb2)

thank you for this! It’s probably the most useful doc I’ve run across

**Comment by rcdailey** [comment]
I'm not completely sure what you're asking for here. The snippet you provided shows the structure of files on the filesystem. However, the reference page you linked is in regards to YAML related to custom formats that isn't related to anything on the filesystem.

Could you please clarify what it is you're wanting?

**Comment by fiservedpi** [comment]
For instance on this [page](https://recyclarr.dev/wiki/yaml/config-examples/) there are a few examples (solutions), but do they go in the config.yaml or sonarr.yaml? Respectively
I was thinking a little tree diagram may be helpful to pinpoint exactly which section a “solution” should be placed in

**Comment by rcdailey** [comment]
Those samples are file-agnostic. How you want to organize your YAML files is up to you. Recyclarr doesn't strictly care about if you have a file named `config.yaml` or `sonarr.yaml` in your `config/configs/` directory. It's entirely your choice.

**Comment by fiservedpi** [comment]
Understood! I get it now just put it in one or the other and it’ll execute
Thanks again.
