### ISSUE TITLE
Improve include file structure requirement docs

### ISSUE THREAD

**Issue by datcactus** [recyclarr/wiki#22]
https://recyclarr.dev/wiki/behavior/include/#file-structure doesn't state that includes won't work at all if they're present in the configs dir and not in the nested includes dir. We mention it in https://recyclarr.dev/wiki/file-structure/#config-directory, but it caused some confusion recently in discord.

Solution: Add wording to https://recyclarr.dev/wiki/behavior/include/#file-structure that makes the behavior/requirements clear

**Comment by rcdailey** [comment]
Thank you for the report. I agree that this area of the documentation needs improvement. I'm going to take it a step further, though. I'm going to make a dedicated `includes` directory for include templates. This will be introduced in v7. In the meantime, I've addressed your concerns on the "next" docs site:

- YAML Behavior page: https://next.recyclarr.dev/wiki/behavior/include/#file-structure
- File Structure page: https://next.recyclarr.dev/wiki/file-structure/#include-directory

Both share the same markdown content on the site.
